### ISSUE TITLE
使用OTSReader抛出异常，联系运维

### ISSUE THREAD

**Issue by iCod1ng** [alibaba/DataX#469]
![QQ截图20191009172308](https://user-images.githubusercontent.com/12381028/66469067-c830c700-eab9-11e9-939d-9a0b11c8c8c9.png)

**Comment by rohit-tiwari-scmp** [comment]
I am having the same problem.

Error: 

WARN ConfigParser-Plug-in [ots-reader, ots-writer] failed to load, try again after 1s ... Exception: Code: [Framework-12], Description: [DataX plug-in initialization error, This problem is usually caused by a DataX installation error , Please contact your operation and maintenance to resolve.].-Plug-in loading failed, loading of the specified plug-in was not completed: [ots-writer, ots-reader]

**Comment by iCod1ng** [comment]
I  already solve this problem. It 's config json demo has some problem. you must config both reader and writer.

**Comment by rohit-tiwari-scmp** [comment]
@iCod1ng  Could you please share sample config, i tried using both reader and writer in the config [ots-writer, ots-reader], but no luck.

**Comment by iCod1ng** [comment]
In My picture,the Log is [otsreader,null],When I  config writer,it's working ; But your  log is [ots-reader, ots-writer]. This may not be the same problem。You can confirm whether the datax compilation is correct and config json is right.My sample is in the attachment。
[ots-demo.txt](https://github.com/alibaba/DataX/files/4012155/ots-demo.txt)

**Comment by dvlp123456** [comment]
thank you, I have the same problem and solve it after view your ots-demo.txt file.

**Comment by iCod1ng** [comment]
> thank you, I have the same problem and solve it after view your ots-demo.txt file.

I'm glad to have been able to help you.  ^_^
