### ISSUE TITLE
mysql导入到elasticsearch报错，提示插件加载失败

### ISSUE THREAD

**Issue by iweisi** [alibaba/DataX#75]
经过测试，发现mysqlreader是没有问题，导出到其他异构数据源没有问题，但是导入到elasticsearch，就会报错，错误信息如下：
2018-04-26 11:50:06.800 [main] WARN  ConfigParser - 插件[mysqlreader,elasticsearchwriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[elasticsearchwriter, mysqlreader] 
2018-04-26 11:50:07.845 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[elasticsearchwriter, mysqlreader]
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

elasticsearchwriter 配置如下：
				"writer": {
					  "name": "elasticsearchwriter",
					  "parameter": {
						"endpoint": "http://xx.xx.xx.xx:9200",            
						"index": "kc21k2",
						"type": "default",
						"cleanup": true,
						"settings": {"index" :{"number_of_shards": 1, "number_of_replicas": 0}},
						"discovery": false,
						"batchSize": 1000,
						"splitter": ",",
						"column": [
						  {"name": "AKC190", "type": "id"},
						  { "name": "AAC001","type": "text" },
						  { "name": "YKC280","type": "text" },
						  { "name": "YKC281","type": "text" },
						  { "name": "AAC003","type": "text" },
						  { "name": "AAC004","type": "text" },
						  { "name": "AAC006","type": "text" },
						  { "name": "AAB001","type": "text" },
						  { "name": "AAB004","type": "text" },
						  { "name": "YAB136","type": "text" },
						  { "name": "YKD105","type": "text" },
						  { "name": "AKB020","type": "text" },
						  { "name": "AKB021","type": "text" }              
						]
					  }
					}

**Comment by xiangwl527** [comment]
因为默认的dataX里面没有elasticsearchwriter插件，这个插件需要下源码来自己编译后手动添加进去。

**Comment by zhonghuazhi** [comment]
提示这个 “/Desktop/ES/datax/plugin/writer/.DS_Store/plugin.json]不存在. 请检查您的配置文件” 
“2018-10-30 14:17:00.566 [main] WARN  ConfigParser - 插件[null,null]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，”

**Comment by zjhiphop** [comment]
我这里也包了相同的错误， 我用的是streamwriter

**Comment by NiuziyuanPy** [comment]
> 因为插件的dataX里面没有elasticsearchwriter插件，这个插件需要下源码来自己编译后手动添加进去。

编译后的包可以发我一下嘛

**Comment by iweisi** [comment]
你好，其实很简单的，就是把DataX源码clone下来，自己编译



---原始邮件---
发件人: "喵喵喵"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 上午9:25
收件人: "alibaba/DataX"<DataX@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"465272694@qq.com"<465272694@qq.com&gt;;
主题: Re: [alibaba/DataX] mysql导入到elasticsearch报错，提示插件加载失败 (#75)




  
因为插件的dataX里面没有elasticsearchwriter插件，这个插件需要下源码来自己编译后手动添加进去。
  
编译后的包可以发我一下嘛

**Comment by NiuziyuanPy** [comment]
我不是做Java 开发的，我没有编译环境

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 465272694@qq.com<mailto:notifications@github.com>
发送时间: 2020年9月17日 9:30
收件人: alibaba/DataX<mailto:DataX@noreply.github.com>
抄送: 喵喵喵<mailto:zzz1364628065@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [alibaba/DataX] mysql导入到elasticsearch报错，提示插件加载失败 (#75)

你好，其实很简单的，就是把DataX源码clone下来，自己编译



---原始邮件---
发件人: "喵喵喵"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 上午9:25
收件人: "alibaba/DataX"<DataX@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"465272694@qq.com"<465272694@qq.com&gt;;
主题: Re: [alibaba/DataX] mysql导入到elasticsearch报错，提示插件加载失败 (#75)





因为插件的dataX里面没有elasticsearchwriter插件，这个插件需要下源码来自己编译后手动添加进去。

编译后的包可以发我一下嘛

―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by NiuziyuanPy** [comment]
可以给一个下载包的连接嘛
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 465272694@qq.com <notifications@github.com>
发送时间: Thursday, September 17, 2020 9:30:21 AM
收件人: alibaba/DataX <DataX@noreply.github.com>
抄送: 喵喵喵 <zzz1364628065@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [alibaba/DataX] mysql导入到elasticsearch报错，提示插件加载失败 (#75)


你好，其实很简单的，就是把DataX源码clone下来，自己编译



---原始邮件---
发件人: "喵喵喵"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 上午9:25
收件人: "alibaba/DataX"<DataX@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"465272694@qq.com"<465272694@qq.com&gt;;
主题: Re: [alibaba/DataX] mysql导入到elasticsearch报错，提示插件加载失败 (#75)





因为插件的dataX里面没有elasticsearchwriter插件，这个插件需要下源码来自己编译后手动添加进去。

编译后的包可以发我一下嘛

―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by rinsonliam** [comment]
> 提示这个 “/Desktop/ES/datax/plugin/writer/.DS_Store/plugin.json]不存在. 请检查您的配置文件”
> “2018-10-30 14:17:00.566 [main] WARN ConfigParser - 插件[null,null]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，”

报不存在问题是因为python的脚本会扫描整个reader和writer目录，发现文件夹的话，都会去目录下找plugin.json文件。Mac系统如果手工修改了writer文件夹里的东西，会默认建一个隐藏文件夹，导致代码检查的时候报错。简单的处理方法是删除.DS_Store的隐藏文件夹即可。
